// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUhyQLI1nWwcZhpl8POXynRaBkOJqGDgM',
    appId: '1:27530728074:web:c38fa694944c916639d373',
    messagingSenderId: '27530728074',
    projectId: 'fir-messaging-195ef',
    authDomain: 'fir-messaging-195ef.firebaseapp.com',
    storageBucket: 'fir-messaging-195ef.appspot.com',
    measurementId: 'G-JJBF16WSZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz5Ldw5WyAxhCkcTA-eGV1-hIjKOjI_Pg',
    appId: '1:27530728074:android:e314452ecb40af6039d373',
    messagingSenderId: '27530728074',
    projectId: 'fir-messaging-195ef',
    storageBucket: 'fir-messaging-195ef.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUhyQLI1nWwcZhpl8POXynRaBkOJqGDgM',
    appId: '1:27530728074:web:a9576dab4b691a1939d373',
    messagingSenderId: '27530728074',
    projectId: 'fir-messaging-195ef',
    authDomain: 'fir-messaging-195ef.firebaseapp.com',
    storageBucket: 'fir-messaging-195ef.appspot.com',
    measurementId: 'G-2XHGX0WDEK',
  );
}
